---
title: "Data Pun TBD"
---

<!---
#### __New Series on Probability & Statistics__

I'm going to be working on a short introduction to Probability & Statistics through a series of posts on the fundamentals of the subjects. Stay tuned and check the content page, or follow my twitter updates for new releases! The first few are already up and more will be coming soon!

-->

#### __Publications__

+ <h><a href="https://www.cjr.org/analysis/election-politics-front-pages.php">Warped Front Pages</a></h>

<!--- + [Other Posts](content.html) -->

#### __Series on Probability and Statistics:__

+ <h><a href="ex3.pdf">Expectation Pt. 4 (Moments) (PDF)</a></h>
+ <h><a href="ex1_2.pdf">Expectation Pt. 3 (Properties of Expectation) (PDF)</a></h>
+ <h><a href="ex2.pdf">Expectation Pt. 2 (Variance) (PDF)</a></h>
+ <h><a href="ex1.pdf">Expectation Pt. 1 (Intro) (PDF)</a></h>
+ [Random Variables Pt. 4 (Markov Chains)](rv4.html)
    + <h><a href="rv4.pdf">(PDF) Random Variables Pt. 4 (Markov Chains)</a></h>
+ [Random Variables Pt. 3 (Functions of a Random Variable)](rv3.html)
    + <h><a href="rv3.pdf">(PDF) Random Variables Pt. 3 (Functions of a Random Variable)</a></h>
+ [Random Variables Pt. 2 (Multivariate Distributions)](rv2.html)
    + <h><a href="rv2.pdf">(PDF) Random Variables Pt. 2 (Multivariate Distributions)</a></h>
+ [Random Variables Pt. 1 (The Basics)](rv1.html)
    + <h><a href="rv_p1.pdf">(PDF) Random Variables Pt. 1 (The Basics)</a></h>
+ <h><a href="bayes_theorem.pdf">Intro to Bayes' Theorem</a></h>
+ <h><a href="conditional_probability.pdf">Basics of Conditional Probability</a></h>

#### __Applied and Unpublished Projects:__ 

+ <h><b><a href="comps.pdf">Optimization Under Uncertainty: The Scenario Approach and Guaranteed Error Machines</a></b></h>
    + [GitHub Link](https://github.com/epickens/Comps)
  + <h><a href="USRESP__Spring_2019___CNN_(3).pdf">Graphical Inference with Convolutional Neural Networks</a></h>
    + [USRESP Alt Link](https://www.causeweb.org/usproc/usresp/2019/spring/winners)
+ <h><a href="dps.pdf">Dynamic Pricing in a Competitive Environment</a></h>
+ <h><a href="nl_is.pdf">Natural Language Image Search</a></h>
+ <h><a href="citibike.pdf">Modeling Citi Bike Availability</a></h>
+ <h><a href="belief_nets.pdf">A Brief Intro to Bayesian Belief Networks</a></h>
    + [GitHub Link](https://github.com/epickens/Bayesian-Networks)
+ [Some Notes on Reinforcement Learning](https://github.com/epickens/Reinforcement-Learning)
+ <h><a href="hmm_draft.pdf">Hidden Markov Models (DRAFT)</a></h>
+ <h><a href="BayesianProject(1).pdf">Replicating Bayesian Distributional Word Embeddings</a></h>
+ <h><a href="Paraphrase_Detection_Final_Writeup.pdf">Paraphrase Detection</a></h>
    + [GitHub Link](https://github.com/chi-raag/paraphraseDetection)
+ [Quick Analysis of Metro Transit Dwell Times](Slides.html)
+ <h><a href="cities.pdf">Quantifiying Smart Growth (With Case Studies in Wellington and Colorado Springs)</a></h>

#### __Miscellaneous Learning Materials:__

+ <h><a href="graphs_pt1.pdf">Graph Analysis and Random Graphs</a></h>
+ <h><a href="online_ski_rental.pdf">Online Algorithms: Ski Rental Problem</a></h>

#### __A few outside posts:__

+ [Carleton Data Science Club](https://carletonalgoclub.github.io/ "Carleton Algo Club")

#### __And the work of some friends:__

+ [Chiraag Gohel](https://chiraaggohel.com/)
+ [Will Dudarov](https://sites.google.com/view/william-dudarov/home?authuser=1)

###### __If you have any questions you can reach me here: [eeepickens@gmail.com](mailto:eeepickens@gmail.com)__

###### __Or check follow me on twitter for real time updates [ElliotPickens](https://twitter.com/ElliotPickens)__


<!--
---
#### __Join this Blog's Google Group__

Get email updates about new posts or changes to the blog through its Google Group. Join [here](http://groups.google.com/group/data-pun-tbd "Data Pun TBD Google Group") or send an email to [data.pun.tbd@gmail.com](mailto:data.pun.tbd@gmail.com).
---
-->
